import {MigrationInterface, QueryRunner} from "typeorm";

export class mockItems1630160008992 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art00', 'MAXALT', 'http://dummyimage.com/207x100.png/dddddd/000000', 'clothes', 'pants', 'Supremacie', 201.78, 51, 8);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art003', 'Phenazopyridine Hydrochloride', 'http://dummyimage.com/211x100.png/dddddd/000000', 'clothes', 'pants', 'Pain Relieving', 72.68, 19, 7);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art004', 'Heparin Sodium', 'http://dummyimage.com/120x100.png/5fa2dd/ffffff', 'clothes', 'T-Shirt', 'anti-bacterial Hand Cleanser', 373.36, 4, 8);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art005', 'Keep the Peace', 'http://dummyimage.com/143x100.png/cc0000/ffffff', 'clothes', 'shoes', 'Tropicamide', 166.32, 78, 2);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art006', 'Dust Mix Antigens', 'http://dummyimage.com/180x100.png/5fa2dd/ffffff', 'clothes', 'socks', 'risperidone', 233.89, 53, 6);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art007', 'Nifedipine', 'http://dummyimage.com/113x100.png/cc0000/ffffff', 'clothes', 'socks', 'Lisinopril', 119.04, 42, 1);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art008', 'RHIZOPUS ARRHIZUS VAR ARRHIZUS', 'http://dummyimage.com/202x100.png/dddddd/000000', 'clothes', 'shoes', 'Indigo Carmine', 330.22, 58, 5);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art009', 'Metamucil', 'http://dummyimage.com/176x100.png/5fa2dd/ffffff', 'clothes', 'socks', 'CHILDRENS DIMETAPP COLD AND ALLERGY', 145.38, 100, 6);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art011', 'Lady Speed Stick', 'http://dummyimage.com/239x100.png/cc0000/ffffff', 'clothes', 'skirt', 'Furosemide', 361.23, 97, 1);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art012', 'Leader Allerhist', 'http://dummyimage.com/155x100.png/5fa2dd/ffffff', 'clothes', 'shoes', 'Heart Small Intestine Meridian Opener', 30.98, 0, 7);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art013', 'Alendronate Sodium', 'http://dummyimage.com/161x100.png/ff4444/ffffff', 'clothes', 'T-Shirt', 'ZONISAMIDE', 228.67, 12, 2);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art014', 'PENICILLIUM CHRYSOGENUM VAR CHRYSOGENUM', 'http://dummyimage.com/248x100.png/dddddd/000000', 'clothes', 'socks', 'Potassium Chloride', 291.09, 90, 2);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art015', 'Bodycology', 'http://dummyimage.com/160x100.png/cc0000/ffffff', 'clothes', 'T-Shirt', '6 CREME 410 TEINTEE', 172.56, 61, 9);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art016', 'Thyreoidea Melissa', 'http://dummyimage.com/127x100.png/dddddd/000000', 'clothes', 'skirt', 'Spironolactone', 47.37, 11, 6);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art017', 'Povidone-Iodine', 'http://dummyimage.com/149x100.png/5fa2dd/ffffff', 'clothes', 'T-Shirt', 'Furosemide', 391.48, 42, 7);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art018', 'PAIN RELIEVER PM', 'http://dummyimage.com/102x100.png/5fa2dd/ffffff', 'clothes', 'skirt', 'Senna-S Laxative', 27.25, 64, 5);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art019', 'Nobacco Remedy Water', 'http://dummyimage.com/243x100.png/cc0000/ffffff', 'clothes', 'shoes', 'Shopko Medicated Lip Treatment', 233.71, 87, 5);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art020', 'PROLASTIN-C', 'http://dummyimage.com/222x100.png/cc0000/ffffff', 'clothes', 'skirt', 'Cold and Cough', 312.66, 13, 2);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art021', 'Leucovorin Calcium', 'http://dummyimage.com/199x100.png/dddddd/000000', 'clothes', 'pants', 'Colgate', 289.64, 65, 4);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art022', 'Minoxidil', 'http://dummyimage.com/118x100.png/ff4444/ffffff', 'clothes', 'skirt', 'Vivierskin Sunscreen', 17.9, 16, 6);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art023', 'Paricalcitol', 'http://dummyimage.com/193x100.png/cc0000/ffffff', 'clothes', 'shoes', 'Dynarex Green', 192.19, 68, 4);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art024', 'Adrenal Support', 'http://dummyimage.com/131x100.png/5fa2dd/ffffff', 'clothes', 'socks', 'Hydrogen Peroxide', 113.24, 18, 6);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art025', 'Advance White Extreme Whitening', 'http://dummyimage.com/218x100.png/ff4444/ffffff', 'clothes', 'socks', 'Zosyn', 364.14, 36, 4);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art026', 'Metoprolol Succinate', 'http://dummyimage.com/176x100.png/5fa2dd/ffffff', 'clothes', 'socks', 'Methocarbamol', 165.92, 63, 3);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art027', 'simvastatin', 'http://dummyimage.com/193x100.png/ff4444/ffffff', 'clothes', 'shoes', 'Tussin', 346.68, 92, 2);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art028', 'Haloperidol', 'http://dummyimage.com/144x100.png/dddddd/000000', 'clothes', 'shoes', 'ACNE TREATMENT SERUM', 165.88, 21, 6);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art029', 'Esomeprazole strontium', 'http://dummyimage.com/139x100.png/dddddd/000000', 'clothes', 'socks', 'InstantFOAM non-alcohol hand sanitizer', 33.79, 64, 8);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art030', 'CVS Pharmacy Nighttime Severe Cough and Cold', 'http://dummyimage.com/195x100.png/dddddd/000000', 'clothes', 'T-Shirt', 'Ready Foundation', 170.4, 95, 3);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art031', 'PANADOL', 'http://dummyimage.com/143x100.png/cc0000/ffffff', 'clothes', 'skirt', 'Meloxicam', 254.99, 7, 10);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art032', 'Ampicillin and Sulbactam', 'http://dummyimage.com/186x100.png/ff4444/ffffff', 'clothes', 'socks', 'Hand Sanitizer', 151.43, 71, 5);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art033', 'Vasopressin', 'http://dummyimage.com/117x100.png/ff4444/ffffff', 'clothes', 'shoes', 'Metronidazole', 19.51, 99, 1);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art034', 'Ammonium Lactate', 'http://dummyimage.com/242x100.png/cc0000/ffffff', 'clothes', 'socks', 'Citalopram Hydrobromide', 208.34, 33, 9);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art035', 'Cefdinir', 'http://dummyimage.com/106x100.png/5fa2dd/ffffff', 'clothes', 'skirt', 'Propranolol Hydrochloride', 184.2, 66, 6);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art036', 'First Aid Original Bacitraycin Plus', 'http://dummyimage.com/204x100.png/cc0000/ffffff', 'clothes', 'T-Shirt', 'Smart Sense Allergy Relief', 93.65, 33, 2);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art037', 'Lisinopril', 'http://dummyimage.com/138x100.png/dddddd/000000', 'clothes', 'T-Shirt', 'Dextrose And Sodium Chloride', 348.68, 4, 1);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art038', 'Aspirin', 'http://dummyimage.com/210x100.png/dddddd/000000', 'clothes', 'skirt', 'Hormeel', 203.33, 46, 5);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art039', 'AIR COMPRESSED', 'http://dummyimage.com/156x100.png/dddddd/000000', 'clothes', 'T-Shirt', 'First Aid', 330.44, 17, 10);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art040', 'Ropinirole Hydrochloride', 'http://dummyimage.com/107x100.png/5fa2dd/ffffff', 'clothes', 'pants', 'GIVEN BY NATURE RICE MASK SHEET', 49.1, 87, 3);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art041', 'Zonisamide', 'http://dummyimage.com/242x100.png/dddddd/000000', 'clothes', 'pants', 'Desert Harvest RELEVEUM', 267.88, 26, 3);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art042', 'POPULUS DELTOIDES POLLEN', 'http://dummyimage.com/173x100.png/dddddd/000000', 'clothes', 'skirt', 'Protective Nail and skin', 308.45, 23, 4);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art043', 'SOLIDAGO CANADENSIS POLLEN', 'http://dummyimage.com/106x100.png/5fa2dd/ffffff', 'clothes', 'pants', 'Childrens Ibuprofen', 304.8, 9, 1);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art044', 'heartburn relief', 'http://dummyimage.com/198x100.png/5fa2dd/ffffff', 'clothes', 'socks', 'Triamterene and Hydrochlorothiazide', 378.14, 23, 9);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art045', 'COCHLIOBOLUS SATIVUS', 'http://dummyimage.com/246x100.png/5fa2dd/ffffff', 'clothes', 'T-Shirt', 'Whole Wheat Grain', 203.8, 34, 2);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art046', 'Montelukast Sodium', 'http://dummyimage.com/196x100.png/ff4444/ffffff', 'accessories', 'shoes', 'Sinus Congestion and Pain Severe', 354.27, 34, 1);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art055', 'Sterile Water', 'http://dummyimage.com/142x100.png/ff4444/ffffff', 'clothes', 'pants', 'Oxycodone and Acetaminophen', 248.09, 26, 10);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art047', 'Oxygen', 'http://dummyimage.com/166x100.png/cc0000/ffffff', 'clothes', 'skirt', 'Montelukast Sodium', 25.7, 37, 5);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art048', 'Healthy Accents hemorrhoidal', 'http://dummyimage.com/216x100.png/cc0000/ffffff', 'clothes', 'T-Shirt', 'Marcaine with Epinephrine', 153.97, 46, 5);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art049', 'Sterile Alcohol Prep Pads', 'http://dummyimage.com/222x100.png/5fa2dd/ffffff', 'clothes', 'skirt', 'Ipratropium Bromide and Albuterol Sulfate', 108.59, 69, 10);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art050', 'Metronidazole', 'http://dummyimage.com/246x100.png/ff4444/ffffff', 'clothes', 'pants', 'Severe Oral Pain Reliever', 367.86, 8, 4);
        insert into item ("itemId", "itemName", "itemPic", "itemClass", "itemType", "itemBrand", price, quantity, "minQuantity") values ('Art052', 'Elta Tar', 'http://dummyimage.com/129x100.png/cc0000/ffffff', 'accessories', 'shoes', 'HYLENEX Recombinant', 242.1, 72, 2);`);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
